[default]
timeout = 120

[i-boss_qletter]
title = "큐레터 저장소"
url = "https://qletter.i-boss.co.kr/list/1/"
entrySelector = "div.innerWrap div.list"
titleSelector = "p strong"
linkSelector = "a"
imageSelector = "div.thumb img"
waitForSelector = "div.list"

[i-boss_popular]
title = "아이보스 ─ 인기글"
url = "https://www.i-boss.co.kr/ab-1886"
entrySelector = "table.table-mbb tbody tr.is_notice_"
titleSelector = "span.mb_subject a span.AB-LF-common"
linkSelector = "span.mb_subject a"
contentSelector = "span.mb_writer"
waitUntil = "networkidle"
