[i-boss_qletter]
title = "큐레터 저장소"
url = "https://qletter.i-boss.co.kr/list/1/"
entrySelector = "div.innerWrap div.list"
titleSelector = "p strong"
linkSelector = "a"
contentSelector = "div.list a p"
imageSelector = "div.thumb img"
waitUntil = "networkidle"

[i-boss_popular]
title = "아이보스 ─ 인기글"
url = "https://www.i-boss.co.kr/ab-1886"
entrySelector = "table.table-mbb tbody tr.is_notice_"
titleSelector = "span.mb_subject a span.AB-LF-common"
linkSelector = "span.mb_subject a"
contentSelector = "span.mb_writer"
dateSelector = "span.bstip"
dateFormat = "MM.dd"
waitUntil = "networkidle"

[i-boss_marketingnews]
title = "아이보스 ─ 마케팅 뉴스"
url = "https://www.i-boss.co.kr/ab-7301"
entrySelector = "div.news-article-list div.cell"
titleSelector = "span.subject_text.text-ellipsis"
linkSelector = "div.info a"
contentSelector = "p.comment_text"
dateSelector = "div.date span.published-date"
dateFormat = "yyyy.MM.dd hh:mm"
imageSelector = "div.img a img"
waitUntil = "networkidle"

[i-boss_news]
title = "아이보스 ─ 뉴스 ─ 전체보기"
url = "https://www.i-boss.co.kr/ab-7214"
entrySelector = "table tbody tr._t:not(:nth-child(1))"
titleSelector = "span.AB-LF-common"
linkSelector = "td:nth-child(2) a"
contentSelector = "p.mb_writer span"
waitUntil = "networkidle"

[i-boss_quiz]
title = "아이보스 ─ 콘텐츠 ─ 마케팅 퀴즈"
url = "https://www.i-boss.co.kr/ab-5826"
entrySelector = "table.question"
titleSelector = "tbody tr:nth-child(1) > td"
linkSelector = "*"
contentSelector = "table.question tbody tr:nth-child(2)"
waitUntil = "networkidle"

[jalnagage_trend_news]
title = "KT 잘나가게 ─ 트렌드/이슈 ─ 소상공인뉴스"
url = "https://jalnagage.kt.co.kr/trend/news/"
entrySelector = "ul.newsList li"
titleSelector = "span.title"
linkSelector = "a"
contentSelector = "span.description"
waitUntil = "networkidle"
