[default]
timeout = 120

[i-boss_qletter]
title = "큐레터 저장소"
url = "https://qletter.i-boss.co.kr/list/1/"
entrySelector = "div.innerWrap div.list"
titleSelector = "p strong"
linkSelector = "a"
contentSelector = "p strong"
imageSelector = "div.thumb img"
waitForSelector = "div.list"
onFail = "stale"
